DEFAULT_INITIAL_CAPITAL = 1_000_000
DEFAULT_TRADE_TIMING = "next_open"
DEFAULT_POSITION_SIZE_PCT = 100.0
DEFAULT_ENTRY_TEXT = "收盤價站上20日均線且外資連買3天"
DEFAULT_EXIT_TEXT = "收盤價跌破20日均線或外資轉賣"
DEFAULT_STRATEGY_TEXT = f"{DEFAULT_ENTRY_TEXT}就買進；{DEFAULT_EXIT_TEXT}就賣出。"

CAPABILITY_GROUPS = [
    {"id": "price_ma", "label": "均線與價格突破", "categories": ["price"]},
    {"id": "volume", "label": "成交量", "categories": ["volume"]},
    {"id": "flow_foreign", "label": "外資買賣", "categories": ["flow_foreign"]},
    {"id": "flow_trust", "label": "投信買賣", "categories": ["flow_trust"]},
    {"id": "flow_dealer", "label": "自營商買賣", "categories": ["flow_dealer"]},
    {"id": "flow_all", "label": "三大法人合計", "categories": ["flow_all"]},
    {"id": "candlestick", "label": "K 棒型態", "categories": ["candlestick"]},
    {"id": "chart_pattern", "label": "技術型態（頭肩、雙頂、V/A 型等）", "categories": ["chart_pattern"]},
    {"id": "risk", "label": "風險控制（停損停利）", "categories": ["risk"]},
]

BACKTEST_CAPABILITY_CATALOG = {
    "groups": CAPABILITY_GROUPS,
    "indicators": [
        # --- 均線與價格突破 ---
        {
            "id": "close_above_ma",
            "category": "price",
            "label": "收盤價站上 N 日均線",
            "aliases": ["站上月線", "站上季線", "站上年線"],
            "examples": ["收盤價站上20日均線", "股價站上月線"],
        },
        {
            "id": "close_below_ma",
            "category": "price",
            "label": "收盤價跌破 N 日均線",
            "aliases": ["跌破月線", "跌破季線", "跌破年線"],
            "examples": ["收盤價跌破20日均線", "股價跌破季線"],
        },
        {
            "id": "ma_golden_cross",
            "category": "price",
            "label": "短均線黃金交叉長均線",
            "aliases": ["黃金交叉", "均線黃金交叉", "短均上穿長均"],
            "examples": ["5日均線黃金交叉20日均線", "10日均線上穿60日均線"],
        },
        {
            "id": "ma_dead_cross",
            "category": "price",
            "label": "短均線死亡交叉長均線",
            "aliases": ["死亡交叉", "均線死叉", "短均下穿長均"],
            "examples": ["5日均線死亡交叉20日均線", "10日均線跌破60日均線"],
        },
        {
            "id": "close_breakout_high",
            "category": "price",
            "label": "收盤價突破 N 日高點",
            "aliases": ["創新高", "突破近高"],
            "examples": ["突破20日高點", "收盤價突破60日高點"],
        },
        {
            "id": "close_breakdown_low",
            "category": "price",
            "label": "收盤價跌破 N 日低點",
            "aliases": ["破底", "跌破近低"],
            "examples": ["跌破20日低點", "收盤價失守60日低點"],
        },
        # --- 成交量 ---
        {
            "id": "volume_above_ma",
            "category": "volume",
            "label": "成交量高於 N 日均量",
            "aliases": ["放量"],
            "examples": ["成交量高於20日均量"],
        },
        {
            "id": "volume_ratio_above_ma",
            "category": "volume",
            "label": "成交量暴增至 N 日均量的 X 倍以上",
            "aliases": ["爆量", "量能暴增", "暴量"],
            "examples": ["成交量暴增至20日均量的1.5倍以上", "成交量大於20日均量2倍"],
        },
        # --- 外資 ---
        {
            "id": "foreign_consecutive_buy",
            "category": "flow_foreign",
            "label": "外資連買 N 天",
            "aliases": ["外資連續買超", "外資連續買"],
            "examples": ["外資連買3天"],
        },
        {
            "id": "foreign_consecutive_sell",
            "category": "flow_foreign",
            "label": "外資連賣 N 天",
            "aliases": ["外資連續賣超"],
            "examples": ["外資連賣3天"],
        },
        {
            "id": "foreign_net_positive",
            "category": "flow_foreign",
            "label": "外資買超",
            "aliases": ["外資淨買", "外資偏多"],
            "examples": ["外資買超"],
        },
        {
            "id": "foreign_net_negative",
            "category": "flow_foreign",
            "label": "外資轉賣 / 賣超",
            "aliases": ["外資轉空", "外資淨賣"],
            "examples": ["外資轉賣", "外資賣超"],
        },
        # --- 投信 ---
        {
            "id": "trust_consecutive_buy",
            "category": "flow_trust",
            "label": "投信連買 N 天",
            "aliases": ["投信連續買超"],
            "examples": ["投信連買3天"],
        },
        {
            "id": "trust_consecutive_sell",
            "category": "flow_trust",
            "label": "投信連賣 N 天",
            "aliases": ["投信連續賣超"],
            "examples": ["投信連賣3天"],
        },
        {
            "id": "trust_net_positive",
            "category": "flow_trust",
            "label": "投信買超",
            "aliases": ["投信淨買"],
            "examples": ["投信買超"],
        },
        {
            "id": "trust_net_negative",
            "category": "flow_trust",
            "label": "投信轉賣 / 賣超",
            "aliases": ["投信轉空"],
            "examples": ["投信轉賣", "投信賣超"],
        },
        # --- 自營商 ---
        {
            "id": "dealer_consecutive_buy",
            "category": "flow_dealer",
            "label": "自營商連買 N 天",
            "aliases": ["自營連買"],
            "examples": ["自營商連買2天"],
        },
        {
            "id": "dealer_consecutive_sell",
            "category": "flow_dealer",
            "label": "自營商連賣 N 天",
            "aliases": ["自營連賣"],
            "examples": ["自營商連賣2天"],
        },
        {
            "id": "dealer_net_positive",
            "category": "flow_dealer",
            "label": "自營商買超",
            "aliases": ["自營買超"],
            "examples": ["自營商買超"],
        },
        {
            "id": "dealer_net_negative",
            "category": "flow_dealer",
            "label": "自營商轉賣 / 賣超",
            "aliases": ["自營賣超"],
            "examples": ["自營商轉賣", "自營商賣超"],
        },
        # --- 三大法人合計 ---
        {
            "id": "all_inst_net_positive",
            "category": "flow_all",
            "label": "三大法人合計買超",
            "aliases": ["法人買超", "主力買超"],
            "examples": ["三大法人買超", "三大法人合計買超"],
        },
        {
            "id": "all_inst_net_negative",
            "category": "flow_all",
            "label": "三大法人合計轉賣 / 賣超",
            "aliases": ["法人轉賣", "主力賣超"],
            "examples": ["三大法人轉賣", "三大法人合計轉賣", "三大法人賣超"],
        },
        # --- K 棒型態（單根） ---
        {
            "id": "candle_doji",
            "category": "candlestick",
            "label": "十字星",
            "aliases": ["十字線", "doji"],
            "examples": ["出現十字星"],
        },
        {
            "id": "candle_hammer",
            "category": "candlestick",
            "label": "錘子線（底部）",
            "aliases": ["錘子", "hammer"],
            "examples": ["下跌後出現錘子線"],
        },
        {
            "id": "candle_hanging_man",
            "category": "candlestick",
            "label": "吊人線（頂部）",
            "aliases": ["吊頸線", "hanging man"],
            "examples": ["上漲後出現吊人線"],
        },
        {
            "id": "candle_shooting_star",
            "category": "candlestick",
            "label": "流星線",
            "aliases": ["射擊之星", "shooting star"],
            "examples": ["上漲後出現流星線"],
        },
        {
            "id": "candle_inverted_hammer",
            "category": "candlestick",
            "label": "倒錘線",
            "aliases": ["倒槌線", "inverted hammer"],
            "examples": ["下跌後出現倒錘線"],
        },
        {
            "id": "candle_long_bullish",
            "category": "candlestick",
            "label": "長紅 / 大陽線",
            "aliases": ["長紅K", "大陽線", "long bullish"],
            "examples": ["出現大陽線"],
        },
        {
            "id": "candle_long_bearish",
            "category": "candlestick",
            "label": "長黑 / 大陰線",
            "aliases": ["長黑K", "大陰線", "long bearish"],
            "examples": ["出現大陰線"],
        },
        # --- K 棒型態（組合） ---
        {
            "id": "candle_bullish_engulfing",
            "category": "candlestick",
            "label": "看漲吞噬 / 多頭吞噬",
            "aliases": ["紅K吞噬", "bullish engulfing"],
            "examples": ["出現看漲吞噬"],
        },
        {
            "id": "candle_bearish_engulfing",
            "category": "candlestick",
            "label": "看跌吞噬 / 空頭吞噬",
            "aliases": ["黑K吞噬", "bearish engulfing"],
            "examples": ["出現看跌吞噬"],
        },
        {
            "id": "candle_three_white_soldiers",
            "category": "candlestick",
            "label": "紅三兵",
            "aliases": ["三白兵", "three white soldiers"],
            "examples": ["出現紅三兵"],
        },
        {
            "id": "candle_three_black_crows",
            "category": "candlestick",
            "label": "三隻烏鴉 / 黑三兵",
            "aliases": ["黑三兵", "三烏鴉", "three black crows"],
            "examples": ["出現黑三兵"],
        },
        {
            "id": "candle_morning_star",
            "category": "candlestick",
            "label": "晨星（底部反轉）",
            "aliases": ["早晨之星", "morning star"],
            "examples": ["出現晨星"],
        },
        {
            "id": "candle_evening_star",
            "category": "candlestick",
            "label": "夜星（頂部反轉）",
            "aliases": ["黃昏之星", "evening star"],
            "examples": ["出現夜星"],
        },
        {
            "id": "candle_bullish_piercing",
            "category": "candlestick",
            "label": "好友反攻 / 刺透",
            "aliases": ["刺透線", "piercing pattern"],
            "examples": ["出現好友反攻"],
        },
        {
            "id": "candle_dark_cloud_cover",
            "category": "candlestick",
            "label": "烏雲蓋頂",
            "aliases": ["烏雲罩頂", "dark cloud cover"],
            "examples": ["出現烏雲蓋頂"],
        },
        # --- 技術型態 ---
        {
            "id": "pattern_head_shoulders_top",
            "category": "chart_pattern",
            "label": "頭肩頂（頂部反轉）",
            "aliases": ["頭肩頂型態", "M 頭加肩", "head and shoulders top"],
            "examples": ["形成頭肩頂"],
        },
        {
            "id": "pattern_head_shoulders_bottom",
            "category": "chart_pattern",
            "label": "頭肩底（底部反轉）",
            "aliases": ["逆頭肩", "頭肩底型態", "inverse head and shoulders"],
            "examples": ["形成頭肩底"],
        },
        {
            "id": "pattern_double_top",
            "category": "chart_pattern",
            "label": "雙頂 / M 頭",
            "aliases": ["M頭", "雙重頂", "double top"],
            "examples": ["形成 M 頭", "雙頂確立"],
        },
        {
            "id": "pattern_double_bottom",
            "category": "chart_pattern",
            "label": "雙底 / W 底",
            "aliases": ["W底", "雙重底", "double bottom"],
            "examples": ["形成 W 底", "雙底確立"],
        },
        {
            "id": "pattern_v_reversal",
            "category": "chart_pattern",
            "label": "V 型反轉（急跌急漲）",
            "aliases": ["V型", "V 反轉", "V reversal"],
            "examples": ["出現 V 型反轉"],
        },
        {
            "id": "pattern_a_reversal",
            "category": "chart_pattern",
            "label": "A 型反轉 / 倒 V（急漲急跌）",
            "aliases": ["倒V", "A型", "A 反轉", "inverted V"],
            "examples": ["出現 A 型反轉", "倒 V 反轉"],
        },
    ],
    "risk_controls": [
        {
            "id": "stop_loss_pct",
            "category": "risk",
            "label": "固定停損",
            "aliases": ["停損", "stop loss"],
            "examples": ["停損8%", "固定停損 10%"],
        },
        {
            "id": "take_profit_pct",
            "category": "risk",
            "label": "固定停利",
            "aliases": ["停利", "take profit"],
            "examples": ["停利20%", "固定停利 15%"],
        },
    ],
    "notes": [
        "目前只支援日線、單檔、long-only、next_open 成交。",
        "自然語言會先走 rule-based 解析，看不懂的條件會丟給 AI 映射到既有 indicator；無法映射才列為 unsupported。",
        "K 棒與技術型態使用固定閾值啟發式判斷，僅供訊號參考，與專業圖學分析可能略有差異。",
    ],
}

BACKTEST_TEMPLATES = [
    {
        "id": "foreign_breakout",
        "name": "外資連買突破型",
        "description": "月線與外資連買確認趨勢續強",
        "entry_text": "收盤價站上20日均線且外資連買3天",
        "exit_text": "收盤價跌破20日均線或外資轉賣",
        "stop_loss_pct": None,
        "take_profit_pct": None,
        "strategy_text": DEFAULT_STRATEGY_TEXT,
    },
    {
        "id": "trust_trend",
        "name": "投信趨勢跟隨型",
        "description": "5日均線黃金交叉20日均線且投信買超時進場",
        "entry_text": "5日均線黃金交叉20日均線且投信買超",
        "exit_text": "5日均線死亡交叉20日均線或投信轉賣",
        "stop_loss_pct": None,
        "take_profit_pct": None,
        "strategy_text": "5日均線黃金交叉20日均線且投信買超就買進；5日均線死亡交叉20日均線或投信轉賣就賣出。",
    },
    {
        "id": "volume_breakout",
        "name": "量價突破型",
        "description": "突破60日高點且量能爆增至1.5倍均量進場",
        "entry_text": "突破60日高點且成交量暴增至20日均量的1.5倍以上",
        "exit_text": "收盤價跌破20日均線",
        "stop_loss_pct": None,
        "take_profit_pct": None,
        "strategy_text": "突破60日高點且成交量暴增至20日均量的1.5倍以上就買進；收盤價跌破20日均線就賣出。",
    },
    {
        "id": "chip_ma_resonance",
        "name": "均線 + 籌碼共振型",
        "description": "站上月線且外資投信同步買超時進場",
        "entry_text": "收盤價站上20日均線且外資買超且投信買超",
        "exit_text": "收盤價跌破20日均線或三大法人合計轉賣",
        "stop_loss_pct": None,
        "take_profit_pct": None,
        "strategy_text": "收盤價站上20日均線且外資買超且投信買超就買進；收盤價跌破20日均線或三大法人合計轉賣就賣出。",
    },
    {
        "id": "ma_golden_cross",
        "name": "均線黃金 / 死亡交叉型",
        "description": "5日均線黃金交叉20日均線時進場，搭配8%停損",
        "entry_text": "5日均線黃金交叉20日均線",
        "exit_text": "5日均線死亡交叉20日均線",
        "stop_loss_pct": 8.0,
        "take_profit_pct": None,
        "strategy_text": "5日均線黃金交叉20日均線就買進；5日均線死亡交叉20日均線或停損8%就賣出。",
    },
    {
        "id": "price_breakout_high",
        "name": "高點突破 + 停利型",
        "description": "收盤價突破20日高點進場，跌破10日低點或停利15%退場",
        "entry_text": "突破20日高點",
        "exit_text": "跌破10日低點",
        "stop_loss_pct": None,
        "take_profit_pct": 15.0,
        "strategy_text": "突破20日高點就買進；跌破10日低點或停利15%就賣出。",
    },
    {
        "id": "triple_ma_trend",
        "name": "多重均線趨勢型",
        "description": "短中長均線同向排列時進場，月線跌破時退場",
        "entry_text": "收盤價站上20日均線且收盤價站上60日均線",
        "exit_text": "收盤價跌破20日均線",
        "stop_loss_pct": None,
        "take_profit_pct": None,
        "strategy_text": "收盤價站上20日均線且收盤價站上60日均線就買進；收盤價跌破20日均線就賣出。",
    },
    {
        "id": "candle_reversal_buy",
        "name": "K 棒底部反轉型",
        "description": "下跌後出現錘子線或紅三兵時進場，跌破月線退場",
        "entry_text": "出現錘子線或出現紅三兵",
        "exit_text": "收盤價跌破20日均線",
        "stop_loss_pct": 8.0,
        "take_profit_pct": None,
        "strategy_text": "出現錘子線或出現紅三兵就買進；收盤價跌破20日均線或停損8%就賣出。",
    },
    {
        "id": "pattern_w_bottom",
        "name": "W 底型態型",
        "description": "形成 W 底進場，跌破頸線或停損 8% 退場",
        "entry_text": "形成 W 底",
        "exit_text": "跌破20日低點",
        "stop_loss_pct": 8.0,
        "take_profit_pct": None,
        "strategy_text": "形成 W 底就買進；跌破20日低點或停損8%就賣出。",
    },
]
